let productsDB = [
  {
    id: 1,
    title: "Headphone item",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    size: "large",
    imageUrl: "images/headphone2.jpeg",
    qty: 1,
    isMe: "N",
  },
  {
    id: 2,
    title: "Labtop item",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    size: "small",
    imageUrl: "images/laptop2.jpeg",
    qty: 1,
    isMe: "N",
  },
  {
    id: 3,
    title: "Watch item",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    size: "medium",
    imageUrl: "images/watch5.jpg",
    qty: 1,
    isMe: "N",
  },
  {
    id: 4,
    title: "Glasses item",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    size: "large",
    imageUrl: "images/glasses2.jpeg",
    qty: 1,
    isMe: "N",
  },
  {
    id: 5,
    title: "Glaves item",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    size: "medium",
    imageUrl: "images/gloves.jpeg",
    qty: 1,
    isMe: "N",
  },
  {
    id: 6,
    title: "Fire item",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    size: "small",
    imageUrl: "images/fire.jpeg",
    qty: 1,
    isMe: "N",
  },
];

// localStorage.setItem("products", JSON.stringify(productsDB));
